import { makeStyles } from "@material-ui/core/styles";
import background from "../../img/cool-background.png";

const useStyles = makeStyles((theme) => ({
  container: {
    backgroundImage: `url(${background})`,
    backgroundPosition: "center",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    padding: 0,
    // height: "49rem",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  paper: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    margin: "1rem 0",
  },
  signIn: {
    color: "#eeeeee",
    lineHeight: "5rem",
    fontWeight: "600",
    // letterSpacing: "2px",
    letterSpacing: "5px",
  },
  avatar: {
    margin: 0,
    backgroundColor: "#00adb5",
    width: "5rem",
    height: "5rem",
    fontSize: "5rem",
  },
  form: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  label: {
    lineHeight: 2,
    textAlign: "left",
    display: "block",
    marginBottom: "13px",
    marginTop: "20px",
    color: "white",
    fontSize: "14px",
    fontWeight: 200,
  },
  input: {
    display: "block",
    boxSizing: "border-box",
    width: "100%",
    borderRadius: "4px",
    border: "1px solid white",
    padding: "10px 15px",
    marginBottom: "10px",
    fontSize: "14px",
  },
  submit: {
    margin: theme.spacing(3, 0, 2),
    background: "#393e46",
    color: "white",
    textTransform: "uppercase",
    border: "none",
    marginTop: "40px",
    padding: "20px",
    fontSize: "16px",
    fontWeight: 100,
    letterSpacing: "10px",
    width: "25%",
    "&:hover": {
      background: "#222831",
      transition: "all 0.4s",
    },
    errNoti: {
      backgroundColor: "#222831",
      color: "#ff2e63",
    },
  },
}));
export default useStyles;
